//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "budgets")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub budget_config_id: Option<i32>,
    pub name: String,
    pub start_date: TimeDate,
    pub end_date: TimeDate,
    pub current_amount: Decimal,
    pub limit: Decimal,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: TimeDateTimeWithTimeZone,
    pub updated_at: TimeDateTimeWithTimeZone,
    pub deleted_at: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::budget_configs::Entity",
        from = "Column::BudgetConfigId",
        to = "super::budget_configs::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    BudgetConfigs,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::budget_configs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BudgetConfigs.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
