//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod prelude;

pub mod budget_configs;
pub mod categories;
pub mod refresh_tokens;
pub mod roles;
pub mod user_roles;
pub mod users;
pub mod wallets;
