//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

#![allow(unused_imports)]

pub use super::budget_configs::Entity as BudgetConfigs;
pub use super::budgets::Entity as Budgets;
pub use super::categories::Entity as Categories;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::roles::Entity as Roles;
pub use super::user_roles::Entity as UserRoles;
pub use super::users::Entity as Users;
pub use super::wallets::Entity as Wallets;
